// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD01zbh_iaPV4l39EMCS73Be4TsZZorXQI',
    appId: '1:650806154318:web:dbf31d5b0ca91ea00b9f1f',
    messagingSenderId: '650806154318',
    projectId: 'database-a626f',
    authDomain: 'database-a626f.firebaseapp.com',
    storageBucket: 'database-a626f.appspot.com',
    measurementId: 'G-T6GM37VDSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArea2cjhZcDuqBxT6r59Hcr-ugM6ygShA',
    appId: '1:650806154318:android:82e80147e40c10460b9f1f',
    messagingSenderId: '650806154318',
    projectId: 'database-a626f',
    storageBucket: 'database-a626f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtHYRX8O8Wao4ADwOMY5Ft8zITzgZWWBQ',
    appId: '1:650806154318:ios:3880840bc3130f5c0b9f1f',
    messagingSenderId: '650806154318',
    projectId: 'database-a626f',
    storageBucket: 'database-a626f.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtHYRX8O8Wao4ADwOMY5Ft8zITzgZWWBQ',
    appId: '1:650806154318:ios:3880840bc3130f5c0b9f1f',
    messagingSenderId: '650806154318',
    projectId: 'database-a626f',
    storageBucket: 'database-a626f.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD01zbh_iaPV4l39EMCS73Be4TsZZorXQI',
    appId: '1:650806154318:web:b92d326f50d36d3a0b9f1f',
    messagingSenderId: '650806154318',
    projectId: 'database-a626f',
    authDomain: 'database-a626f.firebaseapp.com',
    storageBucket: 'database-a626f.appspot.com',
    measurementId: 'G-2X4X09FSKV',
  );
}
